### PR TITLE
Version activation extraction module

### PR DESCRIPTION
**Pull request by complexbrains**
Atm this module is
- LLM specific 
- Extracts activation from a single layer. 

Awaiting adaptations
- Being modal agnostic
- extended to a list of layers

### CODE REVIEW

**Review by maximilienleclei — COMMENTED** [review]
never built this type of class so I don't think I can be that helpful there

**Comment by FrancoisPgm** [comment]
I think `ExtractLayerActivation` doesn't need to be a class, since its `__init__` only set attributes, and it has just one method, you could just write a function that is the method plus the attributes as additional inputs.

**Comment by FrancoisPgm** [comment]
`ExtractActivation` doesn't do much either, so I'd put everything in just one class, which would be `AttachLayerHook` with the `_get_activation`. Also you might want to call `attach_hook` in the `__init__`.

**Comment by FrancoisPgm** [comment]
I don't know how you want to integrate it in your pipeline, but an idea would be to have the attach hook class as a wrapper around your nn.module. So when you instantiate your attach hook class, the object would behave exactly like the nn.module, meaning you can call all its methods, but it would have an additionnal method (or attribute) returning (or holding) the activations.

**Comment by maximilienleclei** [comment]
@complexbrains can we close this?

**Comment by complexbrains** [comment]
oups! so sorry yes we can I guess we incorporated most back then! Doing it now!

**Pull request closed without merging**
