### PR TITLE
Updated docs to focus on core objectives of the library, and leave cn…

### LINKED ISSUE #79: restructure the project overview
currently, the description of the project starts with cneuromod. The library is generic, and could be useful outside of the scope of cneuromod. I am suggesting to add cneuromod as a closing note, and emphasize the features of the libraries right away.

### PR DESCRIPTION
**Pull request by lunebellec**
…euromod as footnote. Fix #79

### CODE REVIEW

**Review by maximilienleclei — APPROVED** [review]
lgtm

**Review by MarieStLaurent — APPROVED** [review]
Looks good to me!

**Comment by lunebellec** [comment]
Thanks @MaximilienLC @MarieStLaurent merging.

**Comment by lunebellec** [comment]
mmmhhh looks I did not squash the commit history. This may be a setting you can add to the repo @MaximilienLC Unsquashed commit history is pretty terrible.

**Comment by maximilienleclei** [comment]
@pbellec squash merging is enabled, haven't found a way to enforce it

**Comment by lunebellec** [comment]
maybe I clicked the wrong button when I merged.

**Pull request merged**
